version: '3'

services:
  fastapi:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql+aiomysql://admin:Iamawesome8425@database-1.cnu2qq6k0mny.us-east-2.rds.amazonaws.com:3306/myappdb
      - SMTP_SERVER=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USER=sandeep.parekh@appvent.co
      - SMTP_PASSWORD=eiwp pbaz pqqj jmgk
      - SECRET_KEY=m5HPpqR2mZFLrQTVD3_o1Um7PtGIoNwRC1yyjO5IWUs
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
