version: '3'

services:
  fastapi:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    env_file: 
      - .env  # Load environment variables from a .env file for better security
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

# Volumes section can be added if needed for persistent storage
volumes:
  redis_data: {}
