name: Deploy FastAPI

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add Droplet SSH Key to known_hosts
        run: |
          ssh-keyscan -H 52.66.236.7 >> ~/.ssh/known_hosts

      - name: SSH and deploy
        run: |
          ssh ubuntu@52.66.236.7 << EOF
          cd /var/www/api_app
          git pull origin master
          docker-compose down
          docker-compose up -d --build
          EOF
